version: '3.8'
services:
  db-local:
    image: postgres:16-alpine
    container_name: pecha-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=pecha
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5434:5432"
    volumes:
      - ./data/db-local:/var/lib/postgresql/data
volumes:
  dbdata6:
